<?php
// $Id$

// Copyright 2007 Thierry GUEGAN http://www.arvoriad.com 

/**
 * @file
 * Defines phone number fields for CCK.
 * Provide some verifications on the phone numbers 
 */

/**
 * Implementation of hook_field_info().
 */
function phone_field_info() {
  return array(
    'fr_phone' => array('label' => t('French Phone Numbers')),
    'ca_phone' => array('label' => t('US & Canadian Phone Numbers')),
   );
}

/**
 * Implementation of hook_field_settings().
 */
function phone_field_settings($op, $field) {      
  switch ($op) {      
    case 'database columns':
      if ($field['type'] == 'fr_phone'){ 
      	$columns = array(
        	'value' => array('type' => 'varchar', 'length' => 255, 'not null' => TRUE),
      	);
      }
      if ($field['type'] == 'ca_phone'){ 
      	$columns = array(
        	'value' => array('type' => 'varchar', 'length' => 255, 'not null' => TRUE),
      	);
      }      
      return $columns;     
  }
}

/**
 * Implementation of hook_field().
 */
function phone_field($op, &$node, $field, &$node_field, $teaser, $page) {
  switch ($op) {
    case 'view':
      foreach ($node_field as $delta => $item) {
        //$node_field[$delta]['view'] = zipcode_field_view_item($field, $item);
        $node_field[$delta]['view'] = content_format($field, $item, 'default', $node);
      }
      return theme('field', $node, $field, $node_field, $teaser, $page); 
  }
}

/**
 * Implementation of hook_field_view_item().
 *
 */
/*
function phone_field_view_item($field, $node_field_item) {
    $phonenumber =  check_plain($node_field_item['value']);
    return $phonenumber;
}
*/
 
/**
 *Implementation of hook_field_formatter_info
 *
 */
function phone_field_formatter_info() {
  return array(
    'default' => array(
      'label' => 'Default',
      'field types' => array('fr_phone', 'ca_phone'),
    ),
  );
 } 
 
/**
* Implementation of hook_field_formatter().
**/
function phone_field_formatter($field, $item, $formatter, $node) {
  if (!isset($item['value'])) {
    return '';
  }
  if ($field['text_processing']) {
    $text = check_markup($item['value'], $item['format'], is_null($node) || isset($node->in_preview));
  }
  else {
    $text = check_plain($item['value']);
  }
  return $text;
}

/**
 * Implementation of hook_widget_info().
 */
function phone_widget_info() {
  return array(
    'phone' => array(
      'label' => t('Textfield'),
      'field types' => array('fr_phone', 'ca_phone'),
    ),
  );
}

/**
 * Implementation of hook_widget_settings().
 */
function phone_widget_settings($op, $widget) {
  switch ($op) {
    case 'form':

    case 'validate':
      break; //do nothing 

    case 'save':
      return array();
  }
}

/**
 * Implementation of hook_widget().
 */
function phone_widget($op, &$node, $field, &$node_field) {
  switch ($op) {   
    case 'form':
      $form = array();
      
      $form[$field['field_name']] = array('#tree' => TRUE);
      
      if ($field['multiple']) {
        $form[$field['field_name']]['#type'] = 'fieldset';
        $form[$field['field_name']]['#title'] = t($field['widget']['label']);
        foreach (range(0,2) as $delta) {
          $form[$field['field_name']][$delta]['value'] = array(
            '#type' => 'textfield',
            '#title' => '',
            '#default_value' => isset($node_field[$delta]['value']) ? $node_field[$delta]['value'] : '',
            '#required' => $field['required'] ? $field['required'] : FALSE,
            '#maxlength' => 255,
            '#weight' => $field['widget']['weight'],
            '#size' => isset($field['widget']['size']) ? $field['widget']['size'] : 20,
          );
        }
      }        
      else {
        $form[$field['field_name']][0]['value'] = array(
          '#type' => 'textfield',
          '#title' => $field['widget']['label'],
          '#default_value' => isset($node_field[0]['value']) ? $node_field[0]['value'] : '',
          '#required' => $field['required'] ? $field['required'] : FALSE,
          '#maxlength' => 255,
          '#weight' => $field['widget']['weight'],
          '#size' => isset($field['widget']['size']) ? $field['widget']['size'] : 20,
        );
      }
               
      return $form;
    
    case 'process form values':
          if (is_array($node_field)) {
            foreach ($node_field as $delta => $item) {
    	    //format the phone number
    	      if ($item['value'] != '') 
	      { 
    	        if ($field['type'] == 'fr_phone') { 
    	          $countrycode = '33'; //33 for France 
	  	  $node_field[0]['value'] = format_fr_phone_number($node_field[0]['value'], $countrycode);
	        }
    	        if ($field['type'] == 'ca_phone') { 
	          $node_field[0]['value'] = format_ca_phone_number($node_field[0]['value']);
	        }
	      }
	    }
	  }
    break;
    
    case 'validate':
      if (is_array($node_field)) {
          foreach ($node_field as $delta => $item) {

	    if ($item['value'] != '') 
	    { 
              if ($field['type'] == 'fr_phone' && !valid_fr_phone_number($item['value'])) {
                form_set_error($field['field_name'],t('"%value" is not a valid French phone number<br>French phone numbers should only contains numbers and spaces and be like 99 99 99 99 99', array('%value' => $item['value'])));
              }
              if ($field['type'] == 'ca_phone' && !valid_ca_phone_number($item['value'])) {
                form_set_error($field['field_name'],t('"%value" is not a valid North American phone number<br>North American Phone numbers should only contains numbers and + and - and ( and ) and spaces and be like 999-999-9999. Please enter a valid ten-digit phone number with optional extension.', array('%value' => $item['value'])));
              }
            }
          }
      }      
      break;
  }                   
}

/**
 * Verification for Phone Numbers.  
 *
 * @param string $phonenumber
 * @return boolean Returns boolean FALSE if the phone number is not valid. 
 */
function valid_fr_phone_number($phonenumber) {

  $phonenumber = trim($phonenumber);

  if (!preg_match("/^(\+){0,1}([0-9 ])*[0-9]$/i",$phonenumber)) { 
  	return false; 
  }
  //right now just do a quick check ==> has to be improved 
  //need to count how many numbers have been filled, ...
  else 
  {
	return true;
  }
}  



/**
 * Verifies that $phonenumber is a valid ten-digit North American phone number
 *
 * @param string $phonenumber
 * @return boolean Returns boolean FALSE if the phone number is not valid. 
 */

function valid_ca_phone_number($phonenumber) {

  $phonenumber = trim($phonenumber);

  // define regular expression
  $regex = "/
    \D*           # ignore non-digits
    1?            # an optional 1
    \D*           # optional separator 
    [02-9]\d{2}   # area code (can't start with 1)
    \D*           # optional separator
    \d{3}         # 3-digit prefix
    \D*           # optional separator
    \d{4}         # 4-digit line number
    \D*           # optional separator
    \d*           # optional extension
    \D*           # ignore trailing non-digits
    /x";
  // return true if valid, false otherwise
  return (bool) preg_match($regex, $phonenumber); 
} 

  	
/**
 * Formatting for Phone Numbers.  
 *
 * @param string $phonenumber
 * @return string Returns a string containting the phone number with some formatting.
 */
function format_fr_phone_number($phonenumber, $countrycode) {

  $phonenumber = trim($phonenumber);

   // do some formatting on the phone number 
   //if doesn't start by '+' add it at the beginning and ins not empty
   if (!preg_match("/^(\+){1}[0-9 ]*$/i",$phonenumber) && !$phonenumber == '') 
   {
	$phonenumber = '+' . $phonenumber;
   }
   //if french phone number, add the country code at the beginning 
   if (!preg_match("/^(\+){1}33[ ]*[0-9 ]*$/i",$phonenumber) && !$phonenumber == '') 
   {
   	$phonenumber = str_replace("+", "+" . $countrycode . " ", $phonenumber);
   }
   return $phonenumber;
}


/**
 * Convert a valid phonenumber into standard (444) 867-5309 x1234 format
 * 
 * @param
 *  $phonenumber must be a valid ten-digit number (with optional extension)
 */
function format_ca_phone_number($phonenumber) {

  // define regular expression   
  $regex = "/
    ^\D*          # ignore non-digits
    1?            # an optional 1
    \D*           # optional separator 
    ([2-9]\d{2})  # capture area code       
    \D*           # optional separator
    ([2-9]\d{2})  # capture 3-digit prefix
    \D*           # optional separator
    (\d{4})       # capture 4-digit line number                       
    \D*           # optional separator
    (\d*)         # capture optional extension                       
    \D*$          # ignore trailing non-digits
  /x"; 
    
  // get digits of phone number
  preg_match($regex, $phonenumber, $matches);
  
  // construct ten-digit phone number
  $phonenumber = $matches[1] . '-' . $matches[2] . '-' . $matches[3];
  
  if ($matches[1] != "1") {
  	$phonenumber = "1" . " " . $phonenumber; 
  }
  
  return $phonenumber;
}